```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, echo = FALSE, message = FALSE, warning = FALSE, results = "hide"
)
```

```{r package_setup}
library(ALA4R)
library(doSNOW)
library(dplyr)
library(dismo)
library(dynatopmodel)
library(foreach)
library(httr)
library(gridExtra)
library(ggplot2)
library(maptools)
library(raster)
library(rgdal)
library(rgeos)
library(sp)
library(scales)
library(rzonation)
library(viridis)
library(voiConsPlan)

ala_config(cache_directory = ".")
```

```{r variables}
resolution <- 1e3L

agg_factor <- 3L

n_bg_points <- 1e4L

n_sp_points <- 30L

n_cl_nodes <- 36L

n_bs_samp <- 1e3L

prop_loss <- .9

projection <- "+init=epsg:28356"

hunter_lgas <- c("Cessnock",       "Dungog",                  "Gloucester",
                 "Gosford",        "Greater Taree",           "Great Lakes",
                 "Lake Macquarie", "Maitland",                "Muswellbrook",
                 "Newcastle",      "Port Macquarie-Hastings", "Port Stephens",
                 "Singleton",      "Upper Hunter",            "Wyong")

predictor_names <- c("Annual Mean Radiation", "Annual Mean Temperature",
                     "Annual Precipitation",  "Precipitation Seasonality", 
                     "Soil Fertility",        "Topographic Wetness")

species_groups  <- c("Birds",               "Mammals",               "Plants")
spp_of_interest <- c("Anthochaera phrygia", "Dasyurus maculatus",    "Acacia bynoeana",
                     "Ninox strenua",       "Petaurus norfolcensis", "Angophora inopina")

spp_max_k  <- c(2e2, 2e2, 2e-2, 1e-2, 1e2, 1e2) %>% setNames(spp_of_interest)

predictor_sources <- c("http://www.abs.gov.au/", "http://www.bom.gov.au/",
                       "http://mapdata.environment.nsw.gov.au/")

predictor_paths <- c("Ausstats/subscriber.nsf/0/56A7AA594A7F44F9CA2578CC0011CE44/$File/1259030001_sla11aaust_shape.zip",
                     "web01/ncc/www/climatology/solar_radiation/solaran.zip",
                     "geonetwork/srv/en/resources.get.archive_OEH")

predictor_queries <-
  list(
    list(), 
    list(), 
    list(
      name = "@", org = "@", email = "@", downloadCateg = "@", comments = "@",
      OEHdownloadLINK = "/Soil_InherentSoilFertilityofNSW.zip"
    )
  )

predictor_dest_files <- c("SLA11aAust.zip", "srad.zip", "soilNSW.zip")

coords <- c("longitude", "latitude")

filters <- c("decimalLatLongConversionFailed", "habitatMismatch",
             "detectedOutlier",                "geodeticDatumAssumedWgs84",
             "nameNotRecognised",              "speciesOutsideExpertRange",
             "coordinatePrecisionMismatch",    "invalidScientificName", 
             "unrecognizedGeodeticDatum",      "invalidGeodeticDatum", 
             "inferredDuplicateRecord")

zonation_settings <- list("removal rule" = 2, "warp factor" = 10)
```

```{r functions}
fmt <- function(x, digits = 0) {
  format(round(x, digits), nsmall = digits, big.mark = ",", scientific = FALSE)
}

get_zip <-
  function(u, p, q, d) {
    GET(
      url = u,
      path = p,
      query = q,
      write_disk(d, overwrite = TRUE)
    )
    unzip(d, overwrite = TRUE, junkpaths = TRUE)
  }

get_bioclim <-
  function(layer, extent, var = "bio") {
    lapply(
      c(xmin, xmax),
      function(x) {
        getData(
          "worldclim",
          var = var,
          res = 0.5,
          lon = do.call(x, list(extent)),
          lat = ymin(extent)
        ) %>%
        crop(extent, snap = "out")
      }
    ) %>%
    do.call(merge, .) %>%
    subset(layer)
  }

dload_records <-
  function(species_group, filters, poly, proj, mask) {
    records <-
      lapply(
        paste0("[", LETTERS, " TO ", paste0(LETTERS, "zzzzz"), "]"),
        function(x) {
          occurrences(
            taxon  = paste0('taxon_name:', x),
            wkt    = writeWKT(gConvexHull(poly)),
            fq     = c(sprintf("species_group:%s", species_group),
                       "coordinate_uncertainty:[0 TO 100]", 
                       "-duplicate_status:D", "geospatial_kosher:true", 
                       "year:[1996 TO 2016]"),
            qa     = filters,
            download_reason_id = 4
          ) %>%
          getElement("data")
      }
    ) %>%
    do.call(rbind, .) %>%
    filter_(paste("!", filters, collapse = "&")) %>%
    select_("species", coords[1], coords[2])
    coordinates(records) <- coords
    proj4string(records) <- "+init=epsg:4326"
    if (!missing(mask)) {
      records <- spTransform(records, CRS(proj4string(mask)))
      records <- records[!is.na(extract(mask, records)), ]
    } else {
      records <- spTransform(records, CRS(proj4string(poly)))
      o <- over(records, poly)
      records <- records[!is.na(o), ]
    }
    spTransform(records, CRS(proj)) %>%
    as.data.frame %>%
    data.frame(species_group = species_group, ., stringsAsFactors = FALSE)
  }

fit_maxent_model <-
  function(sp, data, bg, preds, coords = c("longitude", "latitude"),
           maxent_args = c("hinge=FALSE", "threshold=FALSE"),
           sp_col = "species", sp_grp_col = "species_group",
           bg_sp_grp_col = "species_group") {
    data <- as.data.frame(data)
    bg <- as.data.frame(bg)
    data_sp <- data[, sp_col]
    data_spp_grp <- unique(data[, sp_grp_col])
    bg_spp_grp <- bg[, bg_sp_grp_col]
    maxent(
      x = preds,
      p = data[grepl(gsub(" ", ".*", sp), data_sp), coords],
      a = bg[bg_spp_grp == data_spp_grp, coords],
      args = maxent_args
    )
  }

extract_layers <- function(x, brick_list) lapply(brick_list, raster, layer = x)

as.list.RasterBrick <-
  function(x) lapply(seq_len(nlayers(x)), function(y) raster(x, y))

sd_inv_logit <- function(x) sd(qlogis(x))

mn_plus_ci <- 
  function(x) {
    setNames(
      c(mean(x, na.rm = TRUE), quantile(x, prob = c(.025, .975), na.rm = TRUE)),
      c("mean", "lower95CI", "upper95CI")
    )
  }

ave_prop_rem <-
  function(x, y, p) {
     ans <- cellStats(x * (y > p), sum) / cellStats(x, sum)
     sum(ans, na.rm = TRUE) / nlayers(x)
   }
```

```{r predictor_data}
mapply(get_zip, predictor_sources, predictor_paths, predictor_queries,
       predictor_dest_files)

hunter_poly <- readOGR(".", "SLA11aAust")

hunter_poly <-
  subset(
    hunter_poly,
    SLA_NAME11 %in%
      grep(
        paste(hunter_lgas, collapse = "|"),
        hunter_poly$SLA_NAME11,
        value = TRUE
      )
  ) %>% aggregate

hunter_extent <- extent(hunter_poly)

hunter_alt <-
  getData("alt", country = "AUS") %>%
  crop(hunter_extent, snap = "out") %>% 
  projectRaster(crs = projection, res = resolution)

predictors <-
  list(
    projectRaster(raster("solaran.txt"), hunter_alt),
    projectRaster(get_bioclim(1,  hunter_extent) / 10, hunter_alt),
    projectRaster(get_bioclim(12, hunter_extent), hunter_alt),
    projectRaster(get_bioclim(15, hunter_extent), hunter_alt),
    readOGR(".", "InherentSoilFertility") %>%
      spTransform(CRS(projection)) %>%
      rasterize(hunter_alt, "Fert_value") %>%
      reclassify(cbind(6:7, NA)),
    upslope.area(hunter_alt, atb = TRUE)[["atb"]]
  ) %>%
  setNames(predictor_names) %>%
  brick %>%
  mask(spTransform(hunter_poly, CRS(projection))) %>%
  aggregate(fact = agg_factor)

hunter_alt <-
  hunter_alt %>%
  aggregate(fact = agg_factor) %>%
  mask(calc(predictors, sum))

predictors <- mask(predictors, calc(predictors, sum))

widest_point <- 
  cellFromRow(
    hunter_alt,
    as.matrix(hunter_alt) %>% is.na %>% rowSums %>% which.min
  )
```

```{r occurrence_data}
occurrence_records <-
  lapply(
    species_groups, dload_records, filters, hunter_poly, projection, hunter_alt
  ) %>%
  bind_rows

spp_fltr <-
  paste(gsub(" ", ".*", spp_of_interest), collapse = "|") %>%
  sprintf("grepl('%s', species)", .)

species_occurrences <-
  filter_(occurrence_records, spp_fltr) %>%
  mutate(
    species = factor(gsub(" \\W.*\\W ", " ", species), levels = spp_of_interest)
  ) %>%
  group_by(species) %>%
  sample_n(n_sp_points)

background <-
  filter_(occurrence_records, paste0("!", spp_fltr)) %>%
  group_by(species_group) %>%
  sample_n(n_bg_points)
```

```{r models_boot}
bs_samples <-
  replicate(
    n_bs_samp, 
    sample_n(species_occurrences, n_sp_points, replace = TRUE),
    simplify = FALSE
  )

cl <- makeCluster(n_cl_nodes)
registerDoSNOW(cl)

models_boot <-
  foreach(bs_sample = bs_samples,
          .packages = c("dismo", "dplyr", "voiConsPlan")) %dopar% {
    lapply(spp_of_interest, fit_maxent_model, bs_sample, background,
           predictors) %>%
    lapply(project_maxent, predictors) %>% brick
  }

stopCluster(cl)

models_boot_by_sp <-
  seq_along(spp_of_interest) %>%
  lapply(extract_layers, models_boot) %>%
  lapply(brick)
```

```{r models}
models <- lapply(models_boot_by_sp, calc, mean) %>% brick
```

```{r plan}
plan <- zonation(models, settings = zonation_settings)
```

```{r evwoi}
evwoi <- ave_prop_rem(models, get_rank(plan), prop_loss)
```

```{r plan_boot}
cl <- makeCluster(n_cl_nodes)
registerDoSNOW(cl)

plans_boot <-
  foreach(models = models_boot, .packages = c("dplyr", "rzonation")) %dopar% {
    zonation(models, settings = zonation_settings) %>% get_rank
  }

stopCluster(cl)
```

```{r evwpi}
evwpi <-
  mapply(
    ave_prop_rem, models_boot, plans_boot, MoreArgs = list(p = prop_loss)
  ) %>%
  mean
```
