
Box 3: A simple example of calculating the value of information for a conservation plan using Zonation
------------------------------------------------------------------------------------------------------

In Box 2 we demonstrated how to calculate EVPI for two site conservation plan with continuous uncertainty. Here we extend that problem to 25 sites and two species demonstrate how the problem can be solved using Zonation on random bootstrap samples (Monte Carlo sample) of species distributions. The same method we apply here can be used for much larger numbers of sites and species and is only limited by computing resources.

```{r plot_simple_zonation, fig.cap = "How to calculate the value of information for a conservation plan for 2 species, 25 cells and a budget large enough to purchase 1 cell, using Zonation. First calculate the EVWOI (top row). With original information we rank each cell using the maps of expected (average of $k_1$ and  $k_2$ carrying capacity (top left quadrant). For the highest rank cell (greyed out cell, top right quadrant) take the average proportion of carrying capacity remaining with all other unprotected cells are removed (top equation. Next calculate EVWPI. For each set of bootstrapped species carrying capacity maps $k_1$ and $k_2$ rank each cell and calcualte the average proportion of carrying capacity remaining. The EVWPI is the average of the average proportion of carrying capacity remaining for each bootstrap sample $k_1$ and $k_2$ (middle equation). Finally we calculate EVPI which is the difference between the EVWOI and EVWPI (bottom equation). \\label{fig:plot_simple_zonation}"}
  local(
    {
      build_raster <-
        function(n, n_layers, shape1 = 1, shape2 = 1) {
          dist <- array(NA_real_, dim = c(n + 2, n + 2, n_layers))
          dist[-c(1, n + 2), -c(1, n + 2), ] <-
            array(
              replicate(n_layers, rbeta(n ^ 2, shape1, shape2)),
              dim = c(n, n, n_layers)
            )
          dist
        }
    
      apr <-
        function(loss, pln, fs) {
          mean(
            raster::cellStats(fs * (pln$rasters$rank >= loss), sum) /
              raster::cellStats(fs, sum)
          )
        }
    
      n <- 5
      n_layers <- 2L
      n_species <- 2L
      loss <- ((n ^ 2L) - 1L) / (n ^ 2L)
    
      set.seed(0)
    
      features <- replicate(n_species, build_raster(n, n_layers))
    
      E_features <- raster::brick(apply(features, c(1, 2, 4), mean))
    
      E_plan <- rzonation::zonation(
        E_features,
        settings = list("removal rule" = 2, "edge removal" = 0, "warp factor" = 1)
      )
    
      evwoi <- apr(loss, E_plan, E_features)
    
      dist_features <- apply(features, 3, brick)
    
      dist_plans <-
        lapply(
          dist_features,
          function(x) {
            rzonation::zonation(
              x,
              settings = list(
                "removal rule" = 2, "edge removal" = 0, "warp factor" = 1
                )
              )
          }
        )
    
      vwpi <-
        mapply(
          apr,
          pln = dist_plans,
          fs = dist_features,
          MoreArgs = list(loss = loss),
          SIMPLIFY = TRUE
        )
    
      evwpi <- mean(vwpi)
    
      evpi <- evwpi - evwoi
    
      plot_matrix <-
        function(x, y, nrow, ncol, labels, cell_size, grey_cell = integer(0)) {
        cell_size <- rep(cell_size, length.out =  2)
    
        grey_cell_ind <- arrayInd(grey_cell, .dim = c(nrow, ncol))
    
        for (i in seq_along(grey_cell)) {
          rect(
            x + grey_cell_ind[i, 1] * cell_size[1] - cell_size[1],
            y - grey_cell_ind[i, 2] * cell_size[2],
            x + grey_cell_ind[i, 1] * cell_size[1],
            y - grey_cell_ind[i, 2] * cell_size[2] + cell_size[2],
            col = "grey75",
            border = NA
          )
        }
    
        text(
          rep(
            seq(x, by = cell_size[1], length.out = ncol) + cell_size[1] / 2,
            ncol
          ),
          rep(
            seq(y, by = -cell_size[2], length.out = nrow) - cell_size[2] / 2,
            each = nrow
          ),
          labels = labels
        )
        segments(
          c(rep(x, ncol + 1), seq(x, by = cell_size[1], length.out = ncol + 1)),
          c(seq(y, by = -cell_size[2], length.out = nrow + 1), rep(y, nrow + 1)),
          c(
            rep(x + cell_size[1] * ncol, ncol + 1),
            seq(x, by = cell_size[1], length.out = ncol + 1)
          ),
          c(
            seq(y, by = -cell_size[2], length.out = nrow + 1),
            rep(y - cell_size[2] * nrow, nrow + 1)
          )
        )
      }
    
      tbl <- mapply(
        function(x, y) na.omit(as.integer(t(features[, , x, y]) * 100)),
        rep(1:2, 2),
        rep(1:2, each = 2)
      )
    
      Etbl <- na.omit(apply(E_features[] * 100, 2, as.integer))
    
      ranks <- sapply(
        seq_len(n_layers),
        function(x) {
          rank(
            -na.omit(
              as.numeric(t(raster::as.matrix(dist_plans[[x]]$rasters$rank)))
            )
          )
        }
      )
    
      E_rank <-
        rank(-na.omit(as.numeric(t(raster::as.matrix(E_plan$rasters$rank)))))
    
    
      par(mar = rep(0, 4), ps = 8)
      plot.new()
      plot.window(xlim = c(0, 2.7), ylim = c(0, 2.3))
    
      text(.35, 2.25, "Species 1", pos = 3, cex = 1.3)
      text(.95, 2.25, "Species 2", pos = 3, cex = 1.3)
      text(1.75, 2.25, "Rank", pos = 3, cex = 1.3)
      text(
        .1, 1.95, expression(paste("E[", italic(K), "]")), pos = 2, cex = 1.3
      )
      text(.1, 1.05, expression(italic(k)[1]), pos = 2, cex = 1.3)
      text(.1, .35, expression(italic(k)[2]), pos = 2, cex = 1.3)
      text(.05, c(1.55, .65, -.05), "Total", pos = 3, cex = 1.1)
      segments(.1, 1.45, 2)
      segments(1.35, 2.2, 1.35, .1)
    
      plot_matrix(.1, 2.2, 5, 5, Etbl[, 1], .1, which.min(E_rank))
      text(.35, 1.55, sum(Etbl[, 1]), pos = 3, cex = 1.1)
    
      plot_matrix(.7, 2.2, 5, 5, Etbl[, 2], .1, which.min(E_rank))
      text(.95, 1.55, sum(Etbl[, 2]), pos = 3, cex = 1.1)
    
      plot_matrix(1.5, 2.2, 5, 5, E_rank, .1, which.min(E_rank))
    
      text(
        2.1,
        1.95,
        bquote(
          plain("EVWOI") ==
          frac(
            frac(.(Etbl[which.min(E_rank), 1]), .(sum(Etbl[, 1]))) +
            frac(.(Etbl[which.min(E_rank), 2]), .(sum(Etbl[, 2]))),
            2
          )
        ),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        1.75,
        bquote(phantom(plain("EVWOI")) == .(round(evwoi, 2))),
        pos = 4,
        cex = 1.4
      )
    
      plot_matrix(.1, 1.3, 5, 5, tbl[, 1], .1, which.min(ranks[, 1]))
      text(.35, .65, sum(tbl[, 1]), pos = 3, cex = 1.1)
    
      plot_matrix(.1, .6, 5, 5, tbl[, 2], .1, which.min(ranks[, 2]))
      text(.35, -.05, sum(tbl[, 2]), pos = 3, cex = 1.1)
    
      plot_matrix(.7, 1.3, 5, 5, tbl[, 3], .1, which.min(ranks[, 1]))
      text(.95, .65, sum(tbl[, 3]), pos = 3, cex = 1.1)
    
      plot_matrix(.7, .6, 5, 5, tbl[, 4], .1, which.min(ranks[, 2]))
      text(.95, -.05, sum(tbl[, 4]), pos = 3, cex = 1.1)
    
      plot_matrix(1.5, 1.3, 5, 5, ranks[, 1], .1, which.min(ranks[, 1]))
    
      plot_matrix(1.5, .6, 5, 5, ranks[, 2], .1, which.min(ranks[, 2]))
    
      text(
        2.1,
        1.05,
        bquote(
          plain("EVWPI") ==
            frac(
              frac(
                frac(.(tbl[which.min(ranks[, 1]), 1]), .(sum(tbl[, 1]))) +
                frac(.(tbl[which.min(ranks[, 1]), 3]), .(sum(tbl[, 3]))),
                2
              ) +
              frac(
                frac(.(tbl[which.min(ranks[, 2]), 2]), .(sum(tbl[, 2]))) +
                frac(.(tbl[which.min(ranks[, 2]), 4]), .(sum(tbl[, 4]))),
                2
              ),
              2
            )
        ),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .85,
        bquote(phantom(plain("EVWPI")) == .(round(evwpi, 2))),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .35,
        bquote(plain("EVPI") == plain("EVWPI") - plain("EVWOI")),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .25,
        bquote(
          phantom(plain("EVPI")) == .(round(evwpi, 2)) - .(round(evwoi, 2))
        ),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .15,
        bquote(phantom(plain("EVPI")) == .(round(evpi, 2))),
        pos = 4,
        cex = 1.4
      )
    }
  )
```

Here again, like in Boxes 1 and 2, the planner's aim is to maximise the quality of habitat protected given a limited budget that is large enough to purchase a single property. This time however, there are 25 properties to chose from and two endangered species the planner is entrusted to protect. The planner's aim is to maximise the average (over the two species) proportion of habitat quality remaining after a site has been protected and the remaining 24 have been lost. 

As before, the planner is uncertain about the habitat quality of the 25 sites, and in this case they are uncertain about the habitat quality for both species. The uncertainty in site habitat quality is continuous as in Box 2. In this case habitat quality is measured as the percentage of maximum achievable carrying capacity at a site. For both species the maximum carry capacity of a site is 100, meaning that a site can at most accommodate 100 individuals and a site where the habitat quality is 50% could sustain 50 individuals.

The planner has models that predicts habitat quality for both species. With their model and the computing resources available they are able to produce two bootstrap samples ($k_1$ and $k_2$) of each species modelled distribution. These bootstrapped distribution maps represent the planner's uncertainty of the system state (Figure \ref{fig:plot_simple_zonation}, bottom left quadrant) and with them they can calculate the EVPI.

### Expected value with original information

To calculate EVWOI the planner must calculate the expected value of each site for each species. This amounts to averaging the bootstrapped maps $k_1$ and $k_2$ (Figure \ref{fig:plot_simple_zonation}, top left quadrant). With an bootstrap average map for each species the planner can then find the maximum expected value by building a conservation plan using Zonation. Applying the Zonation software algorithm to the two bootstrapped average maps, the planner finds that the top ranked cell (the cell that best meets the criteria of his objective above) has a habitat quality scores of 77 and 71 percent for species 1 and 2 respectively. To calculate the EVWOI the planner divides these expected values by the total carrying capacity of all sites (to arrive at the proportion of carrying capacity remaining) for each species and then averages that value across species by dividing by two (Figure \ref{fig:plot_simple_zonation}, top equation). In this case the EVWOI is 0.06, that is, relying on the original information alone. the planner would expected to preserve an average of 6% of the initial carry capacity for both species if they protected the best site available and lost the remaining 24.

### Expected value with perfect information

As in Box 2 the planner can apply the same average of Monte Carlo sample expected values method to the bootstrap sample maps they generated here. Again the process of taking the mean (averaging) and maximising (using the Zonation software) is reversed when calculating the EVWPI as opposed to EVWOI. This time the planner creates two conservation plans one for each set of bootstrap sample distribution maps (Figure \ref{fig:plot_simple_zonation}, bottom right quadrant). Each conservation plan gives the planner a different average proportion of total carrying capacity remaining and average over the two gives an EVWPI of 0.7.

### Expected value of perfect information

As in Boxes 1 and 2 the EVPI is the difference between EVWPI and the EVWOI in this case a value of 0.01. This means that the planner would expect on average to increase the average proportion of carrying capacity remaining by 17% if they resolved all their initial uncertainty in their knowledge of habitat suitability of the two species across the 25 sites.
