```{r plot_evwoi_bin_example, fig.cap = caption_evwoi_bin_example}
par(mfrow = c(1, 2), mar = c(0, 1, 3, 3), oma = c(8, 4, 0, 0), lwd = 2, ps = 12)
for (i in 0:1) {
  plot.new()
  plot.window(xlim = 0:1, ylim = 0:1, xaxs = 'i', yaxs = 'i')
  axis(1, at = c(.3, .7), labels = 0:1, lwd = 0, lwd.ticks = 2)
  axis(2, at = {if (!i) c(0, .5, 1) else integer()}, las = 1, lwd = 0,
    lwd.ticks = 2)
  barplot(c({if (i) .4 else .5}, {if (i) .6 else .5}), width = .2, space = 1,
    add = TRUE, border = NA, axes = FALSE, main = paste0('Property ', i + 1))
  if (i) {
    abline(h = .4, lty = 2)
    abline(h = .6, lty = 2)
  } else {
    mtext('Probability', 2, 3)
    abline(h = .5, lty = 2)
  }
  box()
  mtext({if (i) '(0.4' else '(0.5'}, 1, 4, at = .1)
  mtext(expression(phantom(0) %*% phantom(0)), 1, 4, at = .2)
  mtext(' 0)', 1, 4, at = .3) 
  mtext(expression(phantom(0) + phantom(0)), 1, 4, at = .4)
  mtext({if (i) '(0.6' else '(0.5'}, 1, 4, at = .5)
  mtext(expression(phantom(0) %*% phantom(0)), 1, 4, at = .6)
  mtext(' 1)', 1, 4, at = .7)
  mtext('=', 1, 4, at = .8)
  mtext({if (i) '0.6' else '0.5'}, 1, 4, at = .9)
  mtext({if (i) '0.6' else '0.5'}, 1, 5.5, at = .9)
  mtext({if (i) '}'}, 1, 5.5, at = .975)
  mtext({if (!i) 'max {'}, 1, 5.5, at = .75)
  mtext({if (!i) ','}, 1, 5.5, at = .975)
  arrows(
    c(.1, .5, .3, .7), c({if (i) .4 else .5}, {if (i) .6 else .5}, -.15, -.15),
    c(.1, .5, .3, .7), -c(.25, .25, .25, .25), .1, xpd = NA, col = 'grey25',
    lwd = 1
  )
}

mtext('EVWOI', 1, 7, at = 1, adj = 1, font = 2)
mtext('=', 1, 5.5, at = 1.05)
mtext('0.6', 1, 5.5, at = 1.15)
mtext('=', 1, 7, at = 1.05)
mtext('0.6', 1, 7, at = 1.15, font = 2)
mtext('Value', 1, 1, outer = TRUE, adj = -.1)
mtext('Max EV', 1, 5.5, outer = TRUE, adj = -.1, padj = -.1)
mtext('Expected\nvalue (EV)', 1, 4.5, outer = TRUE, adj = -.105, padj = -.3)
rm(i)
```

```{r plot_evwpi_bin_example, fig.cap = caption_evwpi_bin_example}
par(mfrow = c(1, 2), mar = c(0, 1, 3, 1), oma = c(15, 4, 0, 9), lwd = 2,
  ps = 12)
for (i in 0:1) {
  plot.new()
  plot.window(xlim = 0:1, ylim = 0:1, xaxs = 'i', yaxs = 'i')
  axis(1, at = c(.3, .7), labels = 0:1, lwd = 0, lwd.ticks = 2)
  axis(2, at = {if (!i) c(0, .5, 1) else integer()}, las = 1, lwd = 0,
    lwd.ticks = 2)
  barplot(c({if (i) .4 else .5}, {if (i) .6 else .5}), width = .2, space = 1,
    add = TRUE, border = NA, axes = FALSE, main = paste0('Property ', i + 1))
  if (i) {
    abline(h = .4, lty = 2)
    abline(h = .6, lty = 2)
    segments(1, .6, 1.3, .6, xpd = NA, lwd = 1, col = 'grey25')
    arrows(1.3, .6, 1.3, -.4, .1, xpd = NA, lwd = 1, col = 'grey25')
    arrows(1.1, .5, 1.1, -.4, .1, xpd = NA, lwd = 1, col = 'grey25')
  } else {
    mtext('Probability', 2, 3)
    abline(h = .5, lty = 2)
    segments(1, .5, 2.32, .5, xpd = NA, lwd = 1, col = 'grey25')
  }
  box()
  arrows({if (i) c(.3, .7) else c(.7, .3)}, c(-.3, -.3),
    {if (i) c(.3, .7) else c(.7, .3)}, -c(.95, .7), .1,
    col = {
      if (i) c('grey75', 'grey25') else c('grey25', 'grey75')
    }, xpd = NA, lwd = 1)
  for (j in 1:4 * 2 + 3) {
    if (!i) {
      if (j %in% c(5, 11)) {
        mtext({if (j > 9) '(0' else 0}, 1, j, at = .3,
          col = {if (j > 9) 'black' else 'grey75'})
      } else {
        mtext({if (j < 9) '(1' else 1}, 1, j, at = .7,
          col = {if (j < 9) 'black' else 'grey75'})
      }
    } else {
      if (j %in% c(7, 11)) {
        mtext(0, 1, j, at = .3, col = 'grey75')
      } else {
        mtext('(1', 1, j, at = .7)
      }
    }
  }
}
mtext('Value', 1, 1, outer = TRUE, adj = -.1)
mtext('(0.5', 1, 3, at = 1.05)
mtext(expression(phantom(0) %*% phantom(0)), 1, 3,  at = 1.2)
mtext('0.6)', 1, 3, at = 1.35)
mtext('=', 1, 3, at = 1.5)
mtext('0.3', 1, 3, at = 1.65)
arrows(1.5, -.6, 1.5, -.7, .1, xpd = NA, col = 'grey25', lwd = 1)

for (i in 1:4 * 2 + 3) {
  mtext(paste0('Scenario ', (i - 3) / 2), 1, i, outer = TRUE, adj = -.2)
  mtext(expression(phantom(0) %*% phantom(0)), 1, i, at = 1.2)
  mtext({if (i %in% c(7, 11)) '0.2)' else '0.3)'}, 1, i, at = 1.5)
  mtext('=', 1, i, at = 1.7)
  mtext({if (i %in% c(5, 9)) '0.3' else {if (i == 7) '0.2' else 0}}, 1, i,
    at = 1.8)
}
mtext('EVWPI', 1, 13, at = 1.65, adj = 1, font = 2)
mtext('=', 1, 13, at = 1.7)
mtext('0.8', 1, 13, at = 1.8, font = 2)
segments(1.85, -1.8, -1, xpd = NA)
rm(i, j)
```

```{r plot_predictors, fig.cap = caption_predictors}
do.call(
  grid.arrange, 
  c(
    lapply(
      predictor_names,
      function(x) {
        gg_raster(predictors[[gsub(" ", ".", x)]]) +
        ggtitle(x) +
        scale_fill_viridis(na.value = NA, name = "") +
        guides(fill = guide_colourbar(barwidth = 8)) +
        theme(
          plot.title = element_text(size = 11),
          axis.text  = element_blank(),
          axis.title = element_blank(),
          legend.position = "bottom"
        )
      }
    ),
    nrow = 2, 
    padding = 0
  )
)
```

```{r plot_k, fig.cap = caption_predictors}
data_frame(
  `Maximum carrying capacity (individuals/ha)` = spp_max_k,
   species = factor(spp_of_interest, 
                    levels = spp_of_interest[order(spp_max_k)]),
   species_group = rep(species_groups, 2)
) %>%
ggplot +
aes(
  x = species, 
  y = `Maximum carrying capacity (individuals/ha)`,
  fill = species_group
) +
geom_bar(stat = "identity") +
scale_y_continuous(breaks = c(0, 1e-2, 1e-1, 1e0, 1e1, 1e2, 1e3, 1e4)) +
coord_trans(y = trans_new("f", function(x) x ^ (1/4), function(x) x ^ 4)) + 
theme_bw() +
scale_fill_grey(name = "") +
theme(
  axis.title.x = element_blank(),
  axis.text.x  = element_text(angle = 45, hjust = 1, face = "italic")
)
```

```{r plot_occurrences, fig.cap = caption_occurrences}
gg_raster(hunter_alt) +
scale_fill_viridis(
  na.value = NA,
  begin    = 0,
  end      = .6,
  name     = "Altitude\n(m.a.s.l)"
) +
guides(fill = guide_colourbar(barheight = 10)) +
theme(
  axis.text  = element_blank(),
  axis.title = element_blank(),
  strip.text = element_text(face = "italic")
) +
geom_point(
  aes(x = longitude, y = latitude),
  species_occurrences,
  color   = "yellow",
  alpha   = .5,
  size    = .6
) +
facet_wrap(~species, nrow = 2)
```

```{r plot_background, fig.cap = caption_background}
gg_raster(hunter_alt) +
scale_fill_viridis(
  na.value = NA,
  begin    = 0,
  end      = .6,
  name     = "Altitude\n(m.a.s.l)"
) +
guides(fill = guide_colourbar(barheight = 10)) +
theme(axis.text = element_blank(), axis.title = element_blank()) +
geom_point(
  aes(x = longitude, y = latitude),
  background,
  color   = "yellow",
  alpha   = .7,
  size    = .1
) +
facet_wrap( ~species_group, nrow = 1)
```

```{r plot_evwoi_cont_example, fig.cap = caption_evwoi_cont_example}
par(mfrow = c(1, 2), mar = c(0, 1, 3, 3), oma = c(8, 4, 0, 0), lwd = 2, ps = 12)
for (i in 0:1) {
  plot.new()
  plot.window(xlim = 0:1, ylim = 0:1, yaxs = 'i')
  axis(1, at = 0:1, lwd = 0, lwd.ticks = 2)
  curve({if (i) dbeta(x, 2.4, 1.6) / 2 else dbeta(x, 2, 2) / 2}, from = 0, to = 1,
    add = TRUE)
  title(paste0('Property ', i + 1))
  if (i) {
    mtext('0.6', 1, 4, at = .6)
    arrows(.6, dbeta(.6, 2.4, 1.6) / 2, .6, -.25, .1, xpd = NA, col = 'grey25', lwd = 1)
  } else {
    mtext('0.5', 1, 4, at = .5)
    arrows(.5, dbeta(.5, 2, 2) / 2, .5, -.25, .1, xpd = NA, col = 'grey25', lwd = 1)
    mtext('PDF', 2, 1)
  }
  mtext({if (i) '0.6' else '0.5'}, 1, 5.5, at = {if (i) .6 else .5})
  mtext({if (i) '}'}, 1, 5.5, at = {if (i) .675 else .575})
  mtext({if (!i) 'max {'}, 1, 5.5, at = .35)
  mtext({if (!i) ','}, 1, 5.5, at = .575)
  box()
}

mtext('EVWOI', 1, 7, at = 1, adj = 1, font = 2)
mtext('=', 1, 5.5, at = 1.05)
mtext('0.6', 1, 5.5, at = 1.15)
mtext('=', 1, 7, at = 1.05)
mtext('0.6', 1, 7, at = 1.15, font = 2)
mtext('Value', 1, 1, outer = TRUE, adj = -.1)
mtext('Max EV', 1, 5.5, outer = TRUE, adj = -.1, padj = -.1)
mtext('Expected\nvalue (EV)', 1, 4.5, outer = TRUE, adj = -.105, padj = -.3)
rm(i)
```

```{r plot_evwpi_cont_example, fig.cap = caption_evwpi_cont_example}
par(mfrow = c(1, 2), mar = c(0, 1, 3, 3), oma = c(15, 4, 0, 0), lwd = 2, ps = 12)
nsims <- 5

set.seed(34)

sim1 <- replicate(nsims, round(rbeta(1, 2.4, 1.6), 2))
sim2 <- replicate(nsims, round(rbeta(1, 2, 2), 2))
msim <- pmax(sim1, sim2)

for (j in 0:1) {
  plot.new()
  plot.window(xlim = 0:1, ylim = 0:1, yaxs = "i")
  axis(1, at = 0:1, lwd = 0, lwd.ticks = 2)
  if (!j) mtext('PDF', 2, 1)
  curve(
    {
      if (j) dbeta(x, 2.4, 1.6) / 2 else dbeta(x, 2, 2) / 2
    }, 
    from = 0,
    to = 1,
    add = TRUE
  )
  title(paste0("Property ", j + 1))
  box()
  for (i in seq_len(nsims)) {
    if (j) {
      arrows(
        sim1[i],
        dbeta(sim1[i], 2.4, 1.6) / 2,
        sim1[i],
        -.25 - i * .2,
        .1,
        xpd = NA,
        lwd = .5,
        col = "grey"
      )
      text(
        sim1[i], -.25 - i * .2, sim1[i], xpd = NA, adj = c(.25, 1.4),
        col = ifelse(sim1[i] == msim[i], "black", "grey")
        )
    } else {
      arrows(
        sim2[i],
        dbeta(sim2[i], 2, 2) / 2,
        sim2[i],
        -.25 - i * .2,
        .1,
        xpd = NA,
        lwd = .5,
        col = "grey"
      )
      text(
        sim2[i], -.25 - i * .2, sim2[i], xpd = NA, adj = c(.25, 1.4),
        col = ifelse(sim2[i] == msim[i], "black", "grey")
      )
    }
  }
}

mtext("Value", 1, 1, outer = TRUE, adj = -.1)
mtext(
  bquote(
    plain("EVWPI") ==
    frac(.(paste0(msim, collapse = " + ")), .(nsims))
  ),
  1, 12.5, outer = TRUE, adj = 0
)
mtext(
  bquote(
    phantom(plain("EVWPI")) ==
      .(round(mean(msim), 2))
  ),
  1, 13.5, outer = TRUE, adj = 0
)
rm(i, j, msim, nsims, sim1, sim2)
```

```{r plot_models, fig.cap = caption_models}
gg_raster(models, spp_of_interest, 2) +
scale_fill_viridis(na.value = NA, name = "") +
guides(fill = guide_colourbar(barheight = 10)) +
theme(
  axis.text  = element_blank(),
  axis.title = element_blank(),
  strip.text = element_text(face = "italic")
)
```

```{r plot_simple_zonation, fig.cap = caption_simple_zonation}
  local(
    {
      build_raster <-
        function(n, n_layers, shape1 = 1, shape2 = 1) {
          dist <- array(NA_real_, dim = c(n + 2, n + 2, n_layers))
          dist[-c(1, n + 2), -c(1, n + 2), ] <-
            array(
              replicate(n_layers, rbeta(n ^ 2, shape1, shape2)),
              dim = c(n, n, n_layers)
            )
          dist
        }
    
      apr <-
        function(loss, pln, fs) {
          mean(
            raster::cellStats(fs * (pln$rasters$rank >= loss), sum) /
              raster::cellStats(fs, sum)
          )
        }
    
      n <- 5
      n_layers <- 2L
      n_species <- 2L
      loss <- ((n ^ 2L) - 1L) / (n ^ 2L)
    
      set.seed(0)
    
      features <- replicate(n_species, build_raster(n, n_layers))
    
      E_features <- raster::brick(apply(features, c(1, 2, 4), mean))
    
      E_plan <- rzonation::zonation(
        E_features,
        settings = list("removal rule" = 2, "edge removal" = 0, "warp factor" = 1)
      )
    
      evwoi <- apr(loss, E_plan, E_features)
    
      dist_features <- apply(features, 3, brick)
    
      dist_plans <-
        lapply(
          dist_features,
          function(x) {
            rzonation::zonation(
              x,
              settings = list(
                "removal rule" = 2, "edge removal" = 0, "warp factor" = 1
                )
              )
          }
        )
    
      vwpi <-
        mapply(
          apr,
          pln = dist_plans,
          fs = dist_features,
          MoreArgs = list(loss = loss),
          SIMPLIFY = TRUE
        )
    
      evwpi <- mean(vwpi)
    
      evpi <- evwpi - evwoi
    
      plot_matrix <-
        function(x, y, nrow, ncol, labels, cell_size, grey_cell = integer(0)) {
        cell_size <- rep(cell_size, length.out =  2)
    
        grey_cell_ind <- arrayInd(grey_cell, .dim = c(nrow, ncol))
    
        for (i in seq_along(grey_cell)) {
          rect(
            x + grey_cell_ind[i, 1] * cell_size[1] - cell_size[1],
            y - grey_cell_ind[i, 2] * cell_size[2],
            x + grey_cell_ind[i, 1] * cell_size[1],
            y - grey_cell_ind[i, 2] * cell_size[2] + cell_size[2],
            col = "grey75",
            border = NA
          )
        }
    
        text(
          rep(
            seq(x, by = cell_size[1], length.out = ncol) + cell_size[1] / 2,
            ncol
          ),
          rep(
            seq(y, by = -cell_size[2], length.out = nrow) - cell_size[2] / 2,
            each = nrow
          ),
          labels = labels
        )
        segments(
          c(rep(x, ncol + 1), seq(x, by = cell_size[1], length.out = ncol + 1)),
          c(seq(y, by = -cell_size[2], length.out = nrow + 1), rep(y, nrow + 1)),
          c(
            rep(x + cell_size[1] * ncol, ncol + 1),
            seq(x, by = cell_size[1], length.out = ncol + 1)
          ),
          c(
            seq(y, by = -cell_size[2], length.out = nrow + 1),
            rep(y - cell_size[2] * nrow, nrow + 1)
          )
        )
      }
    
      tbl <- mapply(
        function(x, y) na.omit(as.integer(t(features[, , x, y]) * 100)),
        rep(1:2, 2),
        rep(1:2, each = 2)
      )
    
      Etbl <- na.omit(apply(E_features[] * 100, 2, as.integer))
    
      ranks <- sapply(
        seq_len(n_layers),
        function(x) {
          rank(
            -na.omit(
              as.numeric(t(raster::as.matrix(dist_plans[[x]]$rasters$rank)))
            )
          )
        }
      )
    
      E_rank <-
        rank(-na.omit(as.numeric(t(raster::as.matrix(E_plan$rasters$rank)))))
    
    
      par(mar = rep(0, 4), ps = 8)
      plot.new()
      plot.window(xlim = c(0, 2.7), ylim = c(0, 2.3))
    
      text(.35, 2.25, "Species 1", pos = 3, cex = 1.3)
      text(.95, 2.25, "Species 2", pos = 3, cex = 1.3)
      text(1.75, 2.25, "Rank", pos = 3, cex = 1.3)
      text(
        .1, 1.95, expression(paste("E[", italic(K), "]")), pos = 2, cex = 1.3
      )
      text(.1, 1.05, expression(italic(k)[1]), pos = 2, cex = 1.3)
      text(.1, .35, expression(italic(k)[2]), pos = 2, cex = 1.3)
      text(.05, c(1.55, .65, -.05), "Total", pos = 3, cex = 1.1)
      segments(.1, 1.45, 2)
      segments(1.35, 2.2, 1.35, .1)
    
      plot_matrix(.1, 2.2, 5, 5, Etbl[, 1], .1, which.min(E_rank))
      text(.35, 1.55, sum(Etbl[, 1]), pos = 3, cex = 1.1)
    
      plot_matrix(.7, 2.2, 5, 5, Etbl[, 2], .1, which.min(E_rank))
      text(.95, 1.55, sum(Etbl[, 2]), pos = 3, cex = 1.1)
    
      plot_matrix(1.5, 2.2, 5, 5, E_rank, .1, which.min(E_rank))
    
      text(
        2.1,
        1.95,
        bquote(
          plain("EVWOI") ==
          frac(
            frac(.(Etbl[which.min(E_rank), 1]), .(sum(Etbl[, 1]))) +
            frac(.(Etbl[which.min(E_rank), 2]), .(sum(Etbl[, 2]))),
            2
          )
        ),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        1.75,
        bquote(phantom(plain("EVWOI")) == .(round(evwoi, 2))),
        pos = 4,
        cex = 1.4
      )
    
      plot_matrix(.1, 1.3, 5, 5, tbl[, 1], .1, which.min(ranks[, 1]))
      text(.35, .65, sum(tbl[, 1]), pos = 3, cex = 1.1)
    
      plot_matrix(.1, .6, 5, 5, tbl[, 2], .1, which.min(ranks[, 2]))
      text(.35, -.05, sum(tbl[, 2]), pos = 3, cex = 1.1)
    
      plot_matrix(.7, 1.3, 5, 5, tbl[, 3], .1, which.min(ranks[, 1]))
      text(.95, .65, sum(tbl[, 3]), pos = 3, cex = 1.1)
    
      plot_matrix(.7, .6, 5, 5, tbl[, 4], .1, which.min(ranks[, 2]))
      text(.95, -.05, sum(tbl[, 4]), pos = 3, cex = 1.1)
    
      plot_matrix(1.5, 1.3, 5, 5, ranks[, 1], .1, which.min(ranks[, 1]))
    
      plot_matrix(1.5, .6, 5, 5, ranks[, 2], .1, which.min(ranks[, 2]))
    
      text(
        2.1,
        1.05,
        bquote(
          plain("EVWPI") ==
            frac(
              frac(
                frac(.(tbl[which.min(ranks[, 1]), 1]), .(sum(tbl[, 1]))) +
                frac(.(tbl[which.min(ranks[, 1]), 3]), .(sum(tbl[, 3]))),
                2
              ) +
              frac(
                frac(.(tbl[which.min(ranks[, 2]), 2]), .(sum(tbl[, 2]))) +
                frac(.(tbl[which.min(ranks[, 2]), 4]), .(sum(tbl[, 4]))),
                2
              ),
              2
            )
        ),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .85,
        bquote(phantom(plain("EVWPI")) == .(round(evwpi, 2))),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .35,
        bquote(plain("EVPI") == plain("EVWPI") - plain("EVWOI")),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .25,
        bquote(
          phantom(plain("EVPI")) == .(round(evwpi, 2)) - .(round(evwoi, 2))
        ),
        pos = 4,
        cex = 1.4
      )
    
      text(
        2.1,
        .15,
        bquote(phantom(plain("EVPI")) == .(round(evpi, 2))),
        pos = 4,
        cex = 1.4
      )
    }
  )
```

```{r plot_plan, fig.cap = caption_plan}
gg_raster(plan$rasters$rank) +
scale_fill_viridis(na.value = NA, name = "Rank") +
guides(fill = guide_colourbar(barheight = 10, label = FALSE)) +
theme(axis.text = element_blank(), axis.title = element_blank())
```

```{r gg_sd_stack, fig.cap = caption_sd_stack}
lapply(models_boot_by_sp, calc, sd_inv_logit) %>%
brick %>%
gg_raster(spp_of_interest, 2) +
scale_fill_viridis(na.value = NA, name = "") +
guides(fill = guide_colourbar(barheight = 10)) +
theme(
  axis.text  = element_blank(),
  axis.title = element_blank(),
  strip.text = element_text(face = "italic")
)
```

```{r gg_widest_point, fig.cap = caption_widest_point}
lapply(models_boot_by_sp, extract, widest_point) %>%
lapply(apply, 1L, mn_plus_ci) %>%
lapply(t) %>%
lapply(as.data.frame) %>%
mapply(
  cbind, 
  .,
  species = factor(spp_of_interest, levels = spp_of_interest),
  MoreArgs = list(x = seq_along(widest_point)),
  SIMPLIFY = FALSE
) %>%
bind_rows %>%
ggplot +
aes(x = x, y = mean, ymin = lower95CI, ymax = upper95CI) +
geom_ribbon(fill = 'grey') +
geom_line(size = .5) +
theme_bw() +
theme(
  strip.text  = element_text(face = "italic"),
  axis.title  = element_blank(),
  axis.text.x = element_blank()
) +
facet_wrap(~species, nrow = 2)
```

```{r gg_sd_plan, fig.cap = caption_sd_plan}
brick(plans_boot) %>%
calc(sd_inv_logit) %>%
gg_raster +
scale_fill_viridis(na.value = NA, name = "") +
guides(fill = guide_colourbar(barheight = 10)) +
theme(axis.text  = element_blank(), axis.title = element_blank())
```

```{r gg_widest_point_plan, fig.cap = caption_gg_widest_point_plan}
brick(plans_boot) %>%
extract(widest_point) %>%
apply(1L, mn_plus_ci) %>%
t %>%
data.frame(x = seq_along(widest_point)) %>%
ggplot +
aes(x = x, y = mean, ymin = lower95CI, ymax = upper95CI) +
geom_ribbon(fill = 'grey') +
geom_line(size = .5) +
theme_bw() +
theme(
  axis.title  = element_blank(),
  axis.text.x = element_blank()
)
```
