Introduction
============

Spatial conservation planning focuses on developing methods to select candidate sites for protection and other conservation actions [@Moilanen2009]. Spatial conservation plans are complex and their inputs are frequently uncertain because they are based on few data [@Rondinini2006]. The outcomes of spatial conservation plans could always be improved if they incorporated additional information [@Polasky2001]. For example, additional occurrence data could be included for species of concern to the conservation planner, so that the input layers of the spatial plan were more precise. But additional information comes at a cost. And that cost may have to be traded-off against implementing the conservation plan itself. Therefore, it is crucial to measure the value of new information to the conservation plan. If the value of new information is too low, it could be better to implement a plan based on the original information alone, with remaining resources used for direct conservation actions.

Spatial conservation planning and imperfect information
-------------------------------------------------------

Nearly all conservation actions include a spatial component: that is, decisions about where to act. Spatial conservation planning originally focused on designing networks of conservation reserves [@Kirkpatrick1983; @Margules1988], but has expanded to also cover other conservation actions and multi-action planning [e.g., @Westphal2007; @Thomson2009; @Watts2009; @Kujala2015]. An aim of conservation planning is to preserve a comprehensive, adequate and representative subset of a region's biota [@Margules2000] by separating its constituents from threatening processes [@Gaston2002]. States and non-state actors practicing conservation do so with limited budgets and resources [@Naidoo2006]. Therefore, conservation planning must be systematic [@Margules2000].

A typical (systematic) spatial conservation plan will assess a pool of candidate locations for reservation or some equivalent action such as anti-poaching measures [@Plumptre2014]. The planner will either find a set of locations that maximize conservation benefits within a given budget, or prioritize locations in order to meet a conservation target as cost effectively as possible. These are called maximal benefit or minimal set problems respectively [@Cocks1989; @Camm1996]. 

### The information needed to make a spatial conservation plan

A systematic spatial conservation plan is in essence a classic decision problem requiring optimization. Like any problem, it first requires a structured definition. In defining the problem the conservation planner needs five types of information to proceed [@Possingham2001].

* __Objective__: The objective may be a target (e.g., protect 20% of the habitat of a set of species) or a goal to maximize some gain or minimize some loss (e.g. protect locations so as to minimize the average loss of habitat for a set of species.)
* __Constraints__: The bounds in which the plan operates. Including but not limited to, the spatial and temporal frame the plan will operate in, and the resources (e.g., monetary) available to the planner (note that objectives and constraints, depending on context, can be interchangable).
* __Actions__: The actions the planner can take (e.g., protect, not protect, restore habitat, eradicate pests, patrol for poachers, etc.) to meet their objectives within the given constraints.
* __State variables__: The components of the system in which the plan will operate that the planner seeks to effect and against which, the performance of the plan will be measured. In a spatial conservation plan the state variables are typically the distribution of a set of species or habitats the plan is seeking to protect.
* __System models__: A system model links the actions the planner will take and the state variables. With a system model the planner can predict what the outcome of any given plan will be with respect to the state variables of interest (e.g., what will be the effect of protecting certain areas on the distribution and abundance of species).

### Uncertainty in spatial conservation planning.

Of the components in the list above, it is the last two, state variables and system models, where the most critical uncertainty lies. By critical, here we mean uncertainty which could, once addressed, change the decision being made and the decision outcome [@Runge2011]. Here we focus on the uncertainty in state variables and leave the treatment of system model uncertainty for other fora. While in some sense, there may be uncertainty in objectives, constraints and actions, these cannot be critical (in the strict sense we use the term above) as these components define the decision problem itself and thus addressing them is not directly changing the decision and its outcome, it is changing the framework under which the decision maker is operating.

State variables (often modeled species distributions) are almost always based on imperfect knowledge. Conservation planners do not know with certainty where the species they seek to protect occur and must rely on models to predict their occurrence or abundance [@Burgman2005; @Guisan2013]. Such models may themselves be based on uncertain and imperfect inputs (e.g., the distribution of a species may be predicted from a climate envelope that is based on uncertain climate data) [@GuilleraArroita2015]. Uncertainty also arises in state variables, such as species distribution maps, because the models used to build them are trained with a sample of data points. For example, a common approach to predicting the distribution of species is to use so called presence-only species distribution models [@Elith2011]. In such models, the environment of the locations where a species is known to occur, is compared to the distribution of environmental values over the complete landscape under consideration. Ignoring for a moment any uncertainty in the nature of the environment, for a given species, the fewer locations it is known to be present at, the more imprecise and uncertain the predictions of its overall distribution from such models will be.

State variable uncertainty matters to conservation planning because the uncertainty will propagate from inputs all the way through the planning algorithm, to the output and then to the conservation plan. This happens regardless of whether or not the uncertainty is accounted for explicitly.

### Accounting for uncertainty in spatial conservation planning

Ultimately, a conservation planner, like any decision maker, can do one of two things in the face of uncertainty. They can make a decision (formulate a plan) with the uncertainty or try to reduce the uncertainty. Even if they take the second option, uncertainty is rarely completely resolved and the plan must be made with imperfect information. More often than not [though see @Game2008], spatial conservation planning is done in spite of uncertainty rather than by taking any uncertainty into account [@Gaston2003]. Addressing uncertainty has been shown to have clear benefits when making decisions for conservation [@Drechsler2000; @Regan2005] even in reserve design problems [@Moilanen2006].

Uncertainty, whether or not explicit acknowledged, is often not quantified explicitly for the state variables in a conservation plan. Typically a set of species distribution maps will be produced, on top of which a spatial plan is built. However, only one map per species is produced and these maps will be implicitly treated as the state of the system. In reality, the maps represent one possible, and at best, average or most likely (though typically not both and perhaps neither), version of the system state under the assumption that the data used to produce them were unbiased. If instead, a set of maps was produced that reflected the uncertainty (multiple maps for each species) then a complementary set of plans could be produced that reflected the uncertainty in state variables. It is only at this point, having quantified uncertainty, that uncertainty can be addressed and an assessment made of whether, and/or how, to reduce it by acquiring additional information. To know whether or how to reduce uncertainty a conservation planner must measure the value of information [@Polasky2001].

The value of information
------------------------

Value of information analysis is a tool used to quantify how much reducing the uncertainty in a predictive model is worth to a decision maker [@Yokota2004]. The value of information is the difference between the final outcome of a decision (or plan) with or without additional information. Value, in and of itself, cannot be known in advance of the resolution of any decision problem, including a spatial conservation plan. Therefore, decision analysts work with expected value. Expected value is the mean of possible outcomes weighted by their probability of occurring. For example, if a person will earn a dollar when a fair coin toss is heads, and nothing if it is tails, the expected value of the toss is 50 cents. When making a decision with multiple alternatives, assuming the decision maker is risk neutral, it is always best to take the action that maximizes the expected value [@Williams2011].

### The expected value with original information

The expected value with original information, EVWOI, is the maximum expected value if no additional information is gathered before a decision is made (see Box 1). In the case of spatial conservation planning, EVWOI is the default. Typically, a conservation plan maximizes the expected value using the information at hand. For example, species occurrence data (point locations of places where each species of concern has been observed) is used to build a set of species habitat suitability maps, with a species distribution modelling algorithm such as MaxEnt [@Phillips2006]. A second algorithm, such as Zonation [@Moilanen2009] or Marxan [@Ball2009], is used to construct a plan that maximizes (or approximately maximizes) the expected outcome with respect to some objective/target. The key, is that in the default case, there is only one map used per species. The one-per-species map set represents the expected outcome under the present degree of uncertainty. In effect averages of the uncertain species distributions are used, resulting in a conservation plan that represents the expected value with original information.

### The expected value with perfect information

Having perfect information is to have complete knowledge---no uncertainty. While in practice this is unlikely to ever occur, the expected value __with__ perfect information (EVWPI, see Box 1 for a formal definition) is a useful construct as it allows the calculation of the expected value __of__ information.

### The expected value of perfect information

The expected value __of__ perfect information (EVPI) is the difference between EVWPI and EVWOI. If the conservation planner can estimate the value of perfect information, that is, knowing what it is worth to resolve all uncertainty before enacting a conservation plan, then they will have an idea of the upper bound on what they should be willing to do to reduce uncertainty. If the expected value of perfect information is relatively small, then it is less likely to be worth resolving uncertainty than if the value of perfect information was relatively large.

\newpage
```{r box1, child = "box1.rmd"}
```
\newpage

As indicated above, spatial conservation planners rarely explicitly address uncertainty in state variables. This presents a problem, as without measuring uncertainty a conservation planner cannot know whether uncertainty is worth addressing. Without doubt there is a motive to reduce uncertainty in general, as decisions made with less uncertainty, all else being equal, will be better ones than decisions made with relatively more uncertainty [@Reckhow1994]. In light of these facts we propose that the field of spatial conservation planning should absorb the decision theoretic tools of value of information analyses. However, introducing a new tool into to an established framework is by no means trivial. As such, here we seek to incorporate the concepts of value of information in harmony with the norms of systematic spatial conservation planning. In doing so, we outline what we think is the first example of a robust and comprehensive method of calculating the value of information for a spatial conservation plan for the first time. Our approach in the following work has been to balance simplicity with realism. While our central case study is somewhat contrived, it uses real (not simulated) data in a plan to protect species of conservation concern in a region in need of systematic planning [@Whitehead2014; @Kujala2015]. To perform our analysis we combine the use of established software packages MaxEnt [@Phillips2006; @Phillips2008] and Zonation [@Moilanen2009], which are well known to conservation planners, with Monte Carlo resampling methods and a value of information analysis.

The rest of this work is organized as follows. We introduce the case study briefly and then demonstrate how, within the context of spatial conservation planning, the value of information can be calculated using Monte Carlo methods. To aid understanding we interweave the case study with toy, low resolution examples (such as Box 1 above) so that the reader may gain a deeper understanding of the method we are proposing.
