---
title: "The value of information for spatial conservation planning"
author: "William K. Morris, Heini Kujala & Peter A. Vesk"
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: yes
    fig_width: 7.4
    fig_height: 5
    citation_package: natbib
header-includes:
- \linespread{2}\selectfont
- \usepackage{booktabs}
- \usepackage{setspace}
- \usepackage{caption}
- \captionsetup{font={stretch=2}}
- \usepackage{pbox}
- \usepackage[displaymath,mathlines]{lineno}
- \linenumbers
bibliography: voiConsPlan.bib
biblio-style: apalike
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  cache = TRUE, echo = FALSE, message = FALSE, warning = FALSE,
  results = "hide", fig.pos = "!htbp"
)

knitr::opts_knit$set(root.dir = "./build")
```

```{r analyses, child = "analyses.rmd"}
```
\newpage

```{r abstract, child = "abstract.rmd"}
```
\newpage

```{r introduction, child = "introduction.rmd"}
```
\newpage

```{r main_body, child = "main_body.rmd"}
```
\newpage

References
==========

